# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-26 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
